import 'package:flutter/material.dart';
import 'package:jourx/data/response/status.dart';
import 'package:jourx/model/daily_data.dart';
import 'package:jourx/model/diary.dart';
import 'package:jourx/view/widgets/widgets.dart';
import 'package:jourx/view_model/article_viewmodel.dart';
import 'package:jourx/view_model/daily_data_viewmodel.dart';
import 'package:jourx/view_model/diary_viewmodel.dart';
import 'package:jourx/view_model/logout_viewmodel.dart';
import 'package:provider/provider.dart';
import 'package:jourx/view_model/login_viewmodel.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:speech_to_text/speech_to_text.dart' as stt;
import 'package:go_router/go_router.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:jourx/model/model.dart' as Model;
import 'package:fl_chart/fl_chart.dart';

part 'login_page.dart';
part 'register_page.dart';
part 'column_page.dart';
part 'journaling_page.dart';
part 'home_page.dart';
part 'main_menu.dart';
part 'ai_recomendation_page.dart';
part 'history_page.dart';
part 'journal_result_page.dart';
part 'artice_list_page.dart';
part 'article_detail_page.dart';
