// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBud-4Okz6IsuxLyCgITKTEBUhla_EWUrg',
    appId: '1:798911394468:web:503b1ee6cc411600446c31',
    messagingSenderId: '798911394468',
    projectId: 'jourx-c9bc3',
    authDomain: 'jourx-c9bc3.firebaseapp.com',
    storageBucket: 'jourx-c9bc3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq2Y4tRh8Ts6qeB-670Arp3qau-JsbV5k',
    appId: '1:798911394468:android:55a449703137248c446c31',
    messagingSenderId: '798911394468',
    projectId: 'jourx-c9bc3',
    storageBucket: 'jourx-c9bc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNk7WVT1P222JMhAaMpKnnA-2wz6pNofM',
    appId: '1:798911394468:ios:3fdb252bdf9af442446c31',
    messagingSenderId: '798911394468',
    projectId: 'jourx-c9bc3',
    storageBucket: 'jourx-c9bc3.firebasestorage.app',
    iosBundleId: 'com.example.jourx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNk7WVT1P222JMhAaMpKnnA-2wz6pNofM',
    appId: '1:798911394468:ios:3fdb252bdf9af442446c31',
    messagingSenderId: '798911394468',
    projectId: 'jourx-c9bc3',
    storageBucket: 'jourx-c9bc3.firebasestorage.app',
    iosBundleId: 'com.example.jourx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBud-4Okz6IsuxLyCgITKTEBUhla_EWUrg',
    appId: '1:798911394468:web:bb15ebb1a3af86de446c31',
    messagingSenderId: '798911394468',
    projectId: 'jourx-c9bc3',
    authDomain: 'jourx-c9bc3.firebaseapp.com',
    storageBucket: 'jourx-c9bc3.firebasestorage.app',
  );
}
